version: '3.8'

services:
  ##########################
  # AnythingLLM Service
  ##########################
  # anything-llm:
  #   image: mintplexlabs/anythingllm:latest
  #   container_name: anythingllm
  #   cap_add:
  #     - SYS_ADMIN
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3001"   # Web UI accessible at http://localhost:3001
  #     - "8001:8001"   # Internal API
  #   volumes:
  #     - ./data/anythingllm/uploads:/app/uploads  # Documents storage
  #     - ./data/anythingllm/db:/app/db           # Default DB storage
  #     - ./data/anythingllm/storage:/app/server/storage
  #     - ./data/anythingllm/collector/hotdir/:/app/collector/hotdir
  #     - ./data/anythingllm/collector/outputs/:/app/collector/outputs
  #   environment:
  #     STORAGE_DIR: "/app/server/storage"
  #     LLM_PROVIDER: "ollama"        # 'openai' if you have a valid key
  #     OLLAMA_BASE_PATH: "http://ollama:11434"
  #     OLLAMA_MODEL_PREF: 'llama3.2'
  #     EMBEDDING_PROVIDER: "local"
  #     VECTOR_DB: "lancedb"
  #     WHISPER_PROVIDER: "local"
  #    SERVER_PORT: 3001

  ##########################
  # Ollama WebUI Service
  ##########################
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    environment:
      DEBUG: "true"
      OLLAMA_BASE_URL: "http://host.containers.internal:11434"
    volumes:
      - ./data/webui:/app/backend/data
    ports:
      - "3010:8080"

  ##########################
  # Kokoro Service
  ##########################
  kokoro-tts:
    build:
      context: ./Kokoro
      dockerfile: Dockerfile
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    environment:
      - KOKORO_API_KEY=not-needed  # Replace with actual API key if required
      - SERVICE_HOST=kokoro-tts
      - ESPEAK_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libespeak-ng.so.1
   #  - ESPEAK_LIBRARY_PATH=/opt/homebrew/Cellar/espeak-ng/1.52.0/lib/libespeak-ng.1.dylib
    volumes:
      - ./Kokoro/tts_outputs:/app/tts_outputs
      - ./Kokoro/voices:/app/voices
  
    networks:
    default:
      name: my_network
      driver: bridge
