version: '3.8'

services:
  ##########################
  # Ollama WebUI Service
  ##########################
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    environment:
      DEBUG: "true"
      OLLAMA_BASE_URL: "http://host.containers.internal:11434"
    volumes:
      - ./data/webui:/app/backend/data
    ports:
      - "3010:8080"

  ##########################
  # Kokoro Service
  ##########################
  kokoro-tts:
    build:
      context: ./Kokoro
      dockerfile: Dockerfile
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    environment:
      - KOKORO_API_KEY=not-needed  # Replace with actual API key if required
      - SERVICE_HOST=kokoro-tts
      - ESPEAK_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libespeak-ng.so.1
      # - ESPEAK_LIBRARY_PATH=/opt/homebrew/Cellar/espeak-ng/1.52.0/lib/libespeak-ng.1.dylib
    volumes:
      - ./Kokoro/tts_outputs:/app/tts_outputs
      - ./Kokoro/voices:/app/voices
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
